[16/Aug/2017 18:31:14] ERROR [django.request:256] Internal Server Error: /task/12/clueweb12-1805wb-75-02649.html
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/Fan/Downloads/NTCIRMDB2/assessment/views.py", line 242, in show
    return render(request, a+"/"+url)
  File "/Library/Python/2.7/site-packages/django/shortcuts.py", line 67, in render
    template_name, context, request=request, using=using)
  File "/Library/Python/2.7/site-packages/django/template/loader.py", line 98, in render_to_string
    template = get_template(template_name, using=using)
  File "/Library/Python/2.7/site-packages/django/template/loader.py", line 46, in get_template
    raise TemplateDoesNotExist(template_name)
TemplateDoesNotExist: 18/clueweb12-1805wb-75-02649.html
[16/Aug/2017 18:31:15] ERROR [django.request:256] Internal Server Error: /task/12/clueweb12-0208wb-42-00685.html
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/Fan/Downloads/NTCIRMDB2/assessment/views.py", line 242, in show
    return render(request, a+"/"+url)
  File "/Library/Python/2.7/site-packages/django/shortcuts.py", line 67, in render
    template_name, context, request=request, using=using)
  File "/Library/Python/2.7/site-packages/django/template/loader.py", line 98, in render_to_string
    template = get_template(template_name, using=using)
  File "/Library/Python/2.7/site-packages/django/template/loader.py", line 46, in get_template
    raise TemplateDoesNotExist(template_name)
TemplateDoesNotExist: 02/clueweb12-0208wb-42-00685.html
[16/Aug/2017 18:31:16] ERROR [django.request:256] Internal Server Error: /task/12/clueweb12-0812wb-17-18520.html
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/Fan/Downloads/NTCIRMDB2/assessment/views.py", line 242, in show
    return render(request, a+"/"+url)
  File "/Library/Python/2.7/site-packages/django/shortcuts.py", line 67, in render
    template_name, context, request=request, using=using)
  File "/Library/Python/2.7/site-packages/django/template/loader.py", line 98, in render_to_string
    template = get_template(template_name, using=using)
  File "/Library/Python/2.7/site-packages/django/template/loader.py", line 46, in get_template
    raise TemplateDoesNotExist(template_name)
TemplateDoesNotExist: 08/clueweb12-0812wb-17-18520.html
[16/Aug/2017 18:31:19] ERROR [django.request:256] Internal Server Error: /task/12/clueweb12-1101wb-52-16470.html
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/Fan/Downloads/NTCIRMDB2/assessment/views.py", line 242, in show
    return render(request, a+"/"+url)
  File "/Library/Python/2.7/site-packages/django/shortcuts.py", line 67, in render
    template_name, context, request=request, using=using)
  File "/Library/Python/2.7/site-packages/django/template/loader.py", line 98, in render_to_string
    template = get_template(template_name, using=using)
  File "/Library/Python/2.7/site-packages/django/template/loader.py", line 46, in get_template
    raise TemplateDoesNotExist(template_name)
TemplateDoesNotExist: 11/clueweb12-1101wb-52-16470.html
[16/Aug/2017 18:36:29] ERROR [django.request:256] Internal Server Error: /task/12/clueweb12-0100wb-96-34385.html
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/Fan/Downloads/NTCIRMDB2/assessment/views.py", line 242, in show
    return render(request, a+"/"+url)
  File "/Library/Python/2.7/site-packages/django/shortcuts.py", line 67, in render
    template_name, context, request=request, using=using)
  File "/Library/Python/2.7/site-packages/django/template/loader.py", line 98, in render_to_string
    template = get_template(template_name, using=using)
  File "/Library/Python/2.7/site-packages/django/template/loader.py", line 46, in get_template
    raise TemplateDoesNotExist(template_name)
TemplateDoesNotExist: 01/clueweb12-0100wb-96-34385.html
[16/Aug/2017 18:36:31] ERROR [django.request:256] Internal Server Error: /task/12/clueweb12-0406wb-41-15427.html
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/Fan/Downloads/NTCIRMDB2/assessment/views.py", line 242, in show
    return render(request, a+"/"+url)
  File "/Library/Python/2.7/site-packages/django/shortcuts.py", line 67, in render
    template_name, context, request=request, using=using)
  File "/Library/Python/2.7/site-packages/django/template/loader.py", line 98, in render_to_string
    template = get_template(template_name, using=using)
  File "/Library/Python/2.7/site-packages/django/template/loader.py", line 46, in get_template
    raise TemplateDoesNotExist(template_name)
TemplateDoesNotExist: 04/clueweb12-0406wb-41-15427.html
[16/Aug/2017 18:36:32] ERROR [django.request:256] Internal Server Error: /task/12/clueweb12-1903wb-25-10154.html
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/Fan/Downloads/NTCIRMDB2/assessment/views.py", line 242, in show
    return render(request, a+"/"+url)
  File "/Library/Python/2.7/site-packages/django/shortcuts.py", line 67, in render
    template_name, context, request=request, using=using)
  File "/Library/Python/2.7/site-packages/django/template/loader.py", line 98, in render_to_string
    template = get_template(template_name, using=using)
  File "/Library/Python/2.7/site-packages/django/template/loader.py", line 46, in get_template
    raise TemplateDoesNotExist(template_name)
TemplateDoesNotExist: 19/clueweb12-1903wb-25-10154.html
[16/Aug/2017 18:36:32] ERROR [django.request:256] Internal Server Error: /task/12/clueweb12-0209wb-16-00125.html
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/Fan/Downloads/NTCIRMDB2/assessment/views.py", line 242, in show
    return render(request, a+"/"+url)
  File "/Library/Python/2.7/site-packages/django/shortcuts.py", line 67, in render
    template_name, context, request=request, using=using)
  File "/Library/Python/2.7/site-packages/django/template/loader.py", line 98, in render_to_string
    template = get_template(template_name, using=using)
  File "/Library/Python/2.7/site-packages/django/template/loader.py", line 46, in get_template
    raise TemplateDoesNotExist(template_name)
TemplateDoesNotExist: 02/clueweb12-0209wb-16-00125.html
[16/Aug/2017 18:36:33] ERROR [django.request:256] Internal Server Error: /task/12/clueweb12-1808wb-82-19396.html
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/Fan/Downloads/NTCIRMDB2/assessment/views.py", line 242, in show
    return render(request, a+"/"+url)
  File "/Library/Python/2.7/site-packages/django/shortcuts.py", line 67, in render
    template_name, context, request=request, using=using)
  File "/Library/Python/2.7/site-packages/django/template/loader.py", line 98, in render_to_string
    template = get_template(template_name, using=using)
  File "/Library/Python/2.7/site-packages/django/template/loader.py", line 46, in get_template
    raise TemplateDoesNotExist(template_name)
TemplateDoesNotExist: 18/clueweb12-1808wb-82-19396.html
[16/Aug/2017 18:40:30] ERROR [django.request:256] Internal Server Error: /task/12/clueweb12-1808wb-82-19396.html
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/Fan/Downloads/NTCIRMDB2/assessment/views.py", line 242, in show
    return render(request, a+"/"+url)
  File "/Library/Python/2.7/site-packages/django/shortcuts.py", line 67, in render
    template_name, context, request=request, using=using)
  File "/Library/Python/2.7/site-packages/django/template/loader.py", line 98, in render_to_string
    template = get_template(template_name, using=using)
  File "/Library/Python/2.7/site-packages/django/template/loader.py", line 46, in get_template
    raise TemplateDoesNotExist(template_name)
TemplateDoesNotExist: 18/clueweb12-1808wb-82-19396.html
[16/Aug/2017 18:40:33] ERROR [django.request:256] Internal Server Error: /task/13/clueweb12-0305wb-00-15533.html
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/Fan/Downloads/NTCIRMDB2/assessment/views.py", line 242, in show
    return render(request, a+"/"+url)
  File "/Library/Python/2.7/site-packages/django/shortcuts.py", line 67, in render
    template_name, context, request=request, using=using)
  File "/Library/Python/2.7/site-packages/django/template/loader.py", line 98, in render_to_string
    template = get_template(template_name, using=using)
  File "/Library/Python/2.7/site-packages/django/template/loader.py", line 46, in get_template
    raise TemplateDoesNotExist(template_name)
TemplateDoesNotExist: 03/clueweb12-0305wb-00-15533.html
[16/Aug/2017 18:40:36] ERROR [django.request:256] Internal Server Error: /task/13/clueweb12-0107wb-85-24126.html
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/Fan/Downloads/NTCIRMDB2/assessment/views.py", line 242, in show
    return render(request, a+"/"+url)
  File "/Library/Python/2.7/site-packages/django/shortcuts.py", line 67, in render
    template_name, context, request=request, using=using)
  File "/Library/Python/2.7/site-packages/django/template/loader.py", line 98, in render_to_string
    template = get_template(template_name, using=using)
  File "/Library/Python/2.7/site-packages/django/template/loader.py", line 46, in get_template
    raise TemplateDoesNotExist(template_name)
TemplateDoesNotExist: 01/clueweb12-0107wb-85-24126.html
[16/Aug/2017 18:40:38] ERROR [django.request:256] Internal Server Error: /task/13/clueweb12-0803wb-61-25253.html
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/Fan/Downloads/NTCIRMDB2/assessment/views.py", line 242, in show
    return render(request, a+"/"+url)
  File "/Library/Python/2.7/site-packages/django/shortcuts.py", line 67, in render
    template_name, context, request=request, using=using)
  File "/Library/Python/2.7/site-packages/django/template/loader.py", line 98, in render_to_string
    template = get_template(template_name, using=using)
  File "/Library/Python/2.7/site-packages/django/template/loader.py", line 46, in get_template
    raise TemplateDoesNotExist(template_name)
TemplateDoesNotExist: 08/clueweb12-0803wb-61-25253.html
[16/Aug/2017 18:40:39] ERROR [django.request:256] Internal Server Error: /task/13/clueweb12-1314wb-68-05268.html
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/Fan/Downloads/NTCIRMDB2/assessment/views.py", line 242, in show
    return render(request, a+"/"+url)
  File "/Library/Python/2.7/site-packages/django/shortcuts.py", line 67, in render
    template_name, context, request=request, using=using)
  File "/Library/Python/2.7/site-packages/django/template/loader.py", line 98, in render_to_string
    template = get_template(template_name, using=using)
  File "/Library/Python/2.7/site-packages/django/template/loader.py", line 46, in get_template
    raise TemplateDoesNotExist(template_name)
TemplateDoesNotExist: 13/clueweb12-1314wb-68-05268.html
[16/Aug/2017 18:40:42] ERROR [django.request:256] Internal Server Error: /task/12/clueweb12-1808wb-82-19396.html
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/Fan/Downloads/NTCIRMDB2/assessment/views.py", line 242, in show
    return render(request, a+"/"+url)
  File "/Library/Python/2.7/site-packages/django/shortcuts.py", line 67, in render
    template_name, context, request=request, using=using)
  File "/Library/Python/2.7/site-packages/django/template/loader.py", line 98, in render_to_string
    template = get_template(template_name, using=using)
  File "/Library/Python/2.7/site-packages/django/template/loader.py", line 46, in get_template
    raise TemplateDoesNotExist(template_name)
TemplateDoesNotExist: 18/clueweb12-1808wb-82-19396.html
[16/Aug/2017 18:40:47] ERROR [django.request:256] Internal Server Error: /task/11/clueweb12-0712wb-99-12409.html
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/Fan/Downloads/NTCIRMDB2/assessment/views.py", line 242, in show
    return render(request, a+"/"+url)
  File "/Library/Python/2.7/site-packages/django/shortcuts.py", line 67, in render
    template_name, context, request=request, using=using)
  File "/Library/Python/2.7/site-packages/django/template/loader.py", line 98, in render_to_string
    template = get_template(template_name, using=using)
  File "/Library/Python/2.7/site-packages/django/template/loader.py", line 46, in get_template
    raise TemplateDoesNotExist(template_name)
TemplateDoesNotExist: 07/clueweb12-0712wb-99-12409.html
[16/Aug/2017 18:40:51] ERROR [django.request:256] Internal Server Error: /task/12/clueweb12-1808wb-82-19396.html
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/Fan/Downloads/NTCIRMDB2/assessment/views.py", line 242, in show
    return render(request, a+"/"+url)
  File "/Library/Python/2.7/site-packages/django/shortcuts.py", line 67, in render
    template_name, context, request=request, using=using)
  File "/Library/Python/2.7/site-packages/django/template/loader.py", line 98, in render_to_string
    template = get_template(template_name, using=using)
  File "/Library/Python/2.7/site-packages/django/template/loader.py", line 46, in get_template
    raise TemplateDoesNotExist(template_name)
TemplateDoesNotExist: 18/clueweb12-1808wb-82-19396.html
[16/Aug/2017 18:44:12] ERROR [django.request:256] Internal Server Error: /task/12/clueweb12-1808wb-82-19396.html
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/Fan/Downloads/NTCIRMDB2/assessment/views.py", line 242, in show
    return render(request, a+"/"+url)
  File "/Library/Python/2.7/site-packages/django/shortcuts.py", line 67, in render
    template_name, context, request=request, using=using)
  File "/Library/Python/2.7/site-packages/django/template/loader.py", line 98, in render_to_string
    template = get_template(template_name, using=using)
  File "/Library/Python/2.7/site-packages/django/template/loader.py", line 46, in get_template
    raise TemplateDoesNotExist(template_name)
TemplateDoesNotExist: 18/clueweb12-1808wb-82-19396.html
[16/Aug/2017 18:44:16] ERROR [django.request:256] Internal Server Error: /task/12/clueweb12-0203wb-85-11564.html
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/Fan/Downloads/NTCIRMDB2/assessment/views.py", line 242, in show
    return render(request, a+"/"+url)
  File "/Library/Python/2.7/site-packages/django/shortcuts.py", line 67, in render
    template_name, context, request=request, using=using)
  File "/Library/Python/2.7/site-packages/django/template/loader.py", line 98, in render_to_string
    template = get_template(template_name, using=using)
  File "/Library/Python/2.7/site-packages/django/template/loader.py", line 46, in get_template
    raise TemplateDoesNotExist(template_name)
TemplateDoesNotExist: 02/clueweb12-0203wb-85-11564.html
[16/Aug/2017 18:44:18] ERROR [django.request:256] Internal Server Error: /task/12/clueweb12-0208wb-28-26611.html
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/Fan/Downloads/NTCIRMDB2/assessment/views.py", line 242, in show
    return render(request, a+"/"+url)
  File "/Library/Python/2.7/site-packages/django/shortcuts.py", line 67, in render
    template_name, context, request=request, using=using)
  File "/Library/Python/2.7/site-packages/django/template/loader.py", line 98, in render_to_string
    template = get_template(template_name, using=using)
  File "/Library/Python/2.7/site-packages/django/template/loader.py", line 46, in get_template
    raise TemplateDoesNotExist(template_name)
TemplateDoesNotExist: 02/clueweb12-0208wb-28-26611.html
[16/Aug/2017 18:44:26] ERROR [django.request:256] Internal Server Error: /task/12/clueweb12-1008wb-40-28539.html
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/Fan/Downloads/NTCIRMDB2/assessment/views.py", line 242, in show
    return render(request, a+"/"+url)
  File "/Library/Python/2.7/site-packages/django/shortcuts.py", line 67, in render
    template_name, context, request=request, using=using)
  File "/Library/Python/2.7/site-packages/django/template/loader.py", line 98, in render_to_string
    template = get_template(template_name, using=using)
  File "/Library/Python/2.7/site-packages/django/template/loader.py", line 46, in get_template
    raise TemplateDoesNotExist(template_name)
TemplateDoesNotExist: 10/clueweb12-1008wb-40-28539.html
[16/Aug/2017 19:05:19] ERROR [django.request:256] Internal Server Error: /task/12/clueweb12-1808wb-82-19396.html
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/Fan/Downloads/NTCIRMDB2/assessment/views.py", line 255, in show
    return render(request, a+"/"+url)
  File "/Library/Python/2.7/site-packages/django/shortcuts.py", line 67, in render
    template_name, context, request=request, using=using)
  File "/Library/Python/2.7/site-packages/django/template/loader.py", line 98, in render_to_string
    template = get_template(template_name, using=using)
  File "/Library/Python/2.7/site-packages/django/template/loader.py", line 46, in get_template
    raise TemplateDoesNotExist(template_name)
TemplateDoesNotExist: 18/clueweb12-1808wb-82-19396.html
[16/Aug/2017 19:05:26] ERROR [django.request:256] Internal Server Error: /task/12/clueweb12-0401wb-64-21066.html
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/Fan/Downloads/NTCIRMDB2/assessment/views.py", line 255, in show
    return render(request, a+"/"+url)
  File "/Library/Python/2.7/site-packages/django/shortcuts.py", line 67, in render
    template_name, context, request=request, using=using)
  File "/Library/Python/2.7/site-packages/django/template/loader.py", line 98, in render_to_string
    template = get_template(template_name, using=using)
  File "/Library/Python/2.7/site-packages/django/template/loader.py", line 46, in get_template
    raise TemplateDoesNotExist(template_name)
TemplateDoesNotExist: 04/clueweb12-0401wb-64-21066.html
[16/Aug/2017 19:05:29] ERROR [django.request:256] Internal Server Error: /task/12/clueweb12-0106wb-99-24081.html
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/Fan/Downloads/NTCIRMDB2/assessment/views.py", line 255, in show
    return render(request, a+"/"+url)
  File "/Library/Python/2.7/site-packages/django/shortcuts.py", line 67, in render
    template_name, context, request=request, using=using)
  File "/Library/Python/2.7/site-packages/django/template/loader.py", line 98, in render_to_string
    template = get_template(template_name, using=using)
  File "/Library/Python/2.7/site-packages/django/template/loader.py", line 46, in get_template
    raise TemplateDoesNotExist(template_name)
TemplateDoesNotExist: 01/clueweb12-0106wb-99-24081.html
[16/Aug/2017 19:05:31] ERROR [django.request:256] Internal Server Error: /task/12/clueweb12-1808wb-82-19396.html
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/Fan/Downloads/NTCIRMDB2/assessment/views.py", line 255, in show
    return render(request, a+"/"+url)
  File "/Library/Python/2.7/site-packages/django/shortcuts.py", line 67, in render
    template_name, context, request=request, using=using)
  File "/Library/Python/2.7/site-packages/django/template/loader.py", line 98, in render_to_string
    template = get_template(template_name, using=using)
  File "/Library/Python/2.7/site-packages/django/template/loader.py", line 46, in get_template
    raise TemplateDoesNotExist(template_name)
TemplateDoesNotExist: 18/clueweb12-1808wb-82-19396.html
[16/Aug/2017 19:05:32] ERROR [django.request:256] Internal Server Error: /task/12/clueweb12-0401wb-64-21066.html
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/Fan/Downloads/NTCIRMDB2/assessment/views.py", line 255, in show
    return render(request, a+"/"+url)
  File "/Library/Python/2.7/site-packages/django/shortcuts.py", line 67, in render
    template_name, context, request=request, using=using)
  File "/Library/Python/2.7/site-packages/django/template/loader.py", line 98, in render_to_string
    template = get_template(template_name, using=using)
  File "/Library/Python/2.7/site-packages/django/template/loader.py", line 46, in get_template
    raise TemplateDoesNotExist(template_name)
TemplateDoesNotExist: 04/clueweb12-0401wb-64-21066.html
[16/Aug/2017 19:22:30] ERROR [django.request:256] Internal Server Error: /task/12/clueweb12-0106wb-99-24081.html
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/Fan/Downloads/NTCIRMDB2/assessment/views.py", line 251, in show
    return render(request, a+"/"+url)
  File "/Library/Python/2.7/site-packages/django/shortcuts.py", line 67, in render
    template_name, context, request=request, using=using)
  File "/Library/Python/2.7/site-packages/django/template/loader.py", line 98, in render_to_string
    template = get_template(template_name, using=using)
  File "/Library/Python/2.7/site-packages/django/template/loader.py", line 46, in get_template
    raise TemplateDoesNotExist(template_name)
TemplateDoesNotExist: 01/clueweb12-0106wb-99-24081.html
[16/Aug/2017 19:36:57] ERROR [django.request:256] Internal Server Error: /task/12/clueweb12-0106wb-99-24081.html
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/Fan/Downloads/NTCIRMDB2/assessment/views.py", line 251, in show
    return render(request, a+"/"+url)
  File "/Library/Python/2.7/site-packages/django/shortcuts.py", line 67, in render
    template_name, context, request=request, using=using)
  File "/Library/Python/2.7/site-packages/django/template/loader.py", line 98, in render_to_string
    template = get_template(template_name, using=using)
  File "/Library/Python/2.7/site-packages/django/template/loader.py", line 46, in get_template
    raise TemplateDoesNotExist(template_name)
TemplateDoesNotExist: 01/clueweb12-0106wb-99-24081.html
[16/Aug/2017 19:37:00] ERROR [django.request:256] Internal Server Error: /task/12/clueweb12-1202wb-53-20766.html
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/Fan/Downloads/NTCIRMDB2/assessment/views.py", line 251, in show
    return render(request, a+"/"+url)
  File "/Library/Python/2.7/site-packages/django/shortcuts.py", line 67, in render
    template_name, context, request=request, using=using)
  File "/Library/Python/2.7/site-packages/django/template/loader.py", line 98, in render_to_string
    template = get_template(template_name, using=using)
  File "/Library/Python/2.7/site-packages/django/template/loader.py", line 46, in get_template
    raise TemplateDoesNotExist(template_name)
TemplateDoesNotExist: 12/clueweb12-1202wb-53-20766.html
[16/Aug/2017 19:37:01] ERROR [django.request:256] Internal Server Error: /task/12/clueweb12-0106wb-99-24081.html
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/Fan/Downloads/NTCIRMDB2/assessment/views.py", line 251, in show
    return render(request, a+"/"+url)
  File "/Library/Python/2.7/site-packages/django/shortcuts.py", line 67, in render
    template_name, context, request=request, using=using)
  File "/Library/Python/2.7/site-packages/django/template/loader.py", line 98, in render_to_string
    template = get_template(template_name, using=using)
  File "/Library/Python/2.7/site-packages/django/template/loader.py", line 46, in get_template
    raise TemplateDoesNotExist(template_name)
TemplateDoesNotExist: 01/clueweb12-0106wb-99-24081.html
[16/Aug/2017 19:37:24] ERROR [django.request:256] Internal Server Error: /task/12/clueweb12-0106wb-99-24081.html
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/Fan/Downloads/NTCIRMDB2/assessment/views.py", line 251, in show
    return render(request, a+"/"+url)
  File "/Library/Python/2.7/site-packages/django/shortcuts.py", line 67, in render
    template_name, context, request=request, using=using)
  File "/Library/Python/2.7/site-packages/django/template/loader.py", line 98, in render_to_string
    template = get_template(template_name, using=using)
  File "/Library/Python/2.7/site-packages/django/template/loader.py", line 46, in get_template
    raise TemplateDoesNotExist(template_name)
TemplateDoesNotExist: 01/clueweb12-0106wb-99-24081.html
[16/Aug/2017 19:37:27] ERROR [django.request:256] Internal Server Error: /task/12/clueweb12-1202wb-53-20766.html
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/Fan/Downloads/NTCIRMDB2/assessment/views.py", line 251, in show
    return render(request, a+"/"+url)
  File "/Library/Python/2.7/site-packages/django/shortcuts.py", line 67, in render
    template_name, context, request=request, using=using)
  File "/Library/Python/2.7/site-packages/django/template/loader.py", line 98, in render_to_string
    template = get_template(template_name, using=using)
  File "/Library/Python/2.7/site-packages/django/template/loader.py", line 46, in get_template
    raise TemplateDoesNotExist(template_name)
TemplateDoesNotExist: 12/clueweb12-1202wb-53-20766.html
[16/Aug/2017 19:37:29] ERROR [django.request:256] Internal Server Error: /task/12/clueweb12-0106wb-99-24081.html
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/Fan/Downloads/NTCIRMDB2/assessment/views.py", line 251, in show
    return render(request, a+"/"+url)
  File "/Library/Python/2.7/site-packages/django/shortcuts.py", line 67, in render
    template_name, context, request=request, using=using)
  File "/Library/Python/2.7/site-packages/django/template/loader.py", line 98, in render_to_string
    template = get_template(template_name, using=using)
  File "/Library/Python/2.7/site-packages/django/template/loader.py", line 46, in get_template
    raise TemplateDoesNotExist(template_name)
TemplateDoesNotExist: 01/clueweb12-0106wb-99-24081.html
[16/Aug/2017 19:37:30] ERROR [django.request:256] Internal Server Error: /task/12/clueweb12-1202wb-53-20766.html
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/Fan/Downloads/NTCIRMDB2/assessment/views.py", line 251, in show
    return render(request, a+"/"+url)
  File "/Library/Python/2.7/site-packages/django/shortcuts.py", line 67, in render
    template_name, context, request=request, using=using)
  File "/Library/Python/2.7/site-packages/django/template/loader.py", line 98, in render_to_string
    template = get_template(template_name, using=using)
  File "/Library/Python/2.7/site-packages/django/template/loader.py", line 46, in get_template
    raise TemplateDoesNotExist(template_name)
TemplateDoesNotExist: 12/clueweb12-1202wb-53-20766.html
[16/Aug/2017 19:37:32] ERROR [django.request:256] Internal Server Error: /task/12/clueweb12-1602wb-05-03159.html
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/Fan/Downloads/NTCIRMDB2/assessment/views.py", line 251, in show
    return render(request, a+"/"+url)
  File "/Library/Python/2.7/site-packages/django/shortcuts.py", line 67, in render
    template_name, context, request=request, using=using)
  File "/Library/Python/2.7/site-packages/django/template/loader.py", line 98, in render_to_string
    template = get_template(template_name, using=using)
  File "/Library/Python/2.7/site-packages/django/template/loader.py", line 46, in get_template
    raise TemplateDoesNotExist(template_name)
TemplateDoesNotExist: 16/clueweb12-1602wb-05-03159.html
[16/Aug/2017 19:37:33] ERROR [django.request:256] Internal Server Error: /task/12/clueweb12-1515wb-61-17812.html
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/Fan/Downloads/NTCIRMDB2/assessment/views.py", line 251, in show
    return render(request, a+"/"+url)
  File "/Library/Python/2.7/site-packages/django/shortcuts.py", line 67, in render
    template_name, context, request=request, using=using)
  File "/Library/Python/2.7/site-packages/django/template/loader.py", line 98, in render_to_string
    template = get_template(template_name, using=using)
  File "/Library/Python/2.7/site-packages/django/template/loader.py", line 46, in get_template
    raise TemplateDoesNotExist(template_name)
TemplateDoesNotExist: 15/clueweb12-1515wb-61-17812.html
[16/Aug/2017 19:37:36] ERROR [django.request:256] Internal Server Error: /task/12/clueweb12-1712wb-72-05083.html
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/Fan/Downloads/NTCIRMDB2/assessment/views.py", line 251, in show
    return render(request, a+"/"+url)
  File "/Library/Python/2.7/site-packages/django/shortcuts.py", line 67, in render
    template_name, context, request=request, using=using)
  File "/Library/Python/2.7/site-packages/django/template/loader.py", line 98, in render_to_string
    template = get_template(template_name, using=using)
  File "/Library/Python/2.7/site-packages/django/template/loader.py", line 46, in get_template
    raise TemplateDoesNotExist(template_name)
TemplateDoesNotExist: 17/clueweb12-1712wb-72-05083.html
[08/Nov/2017 15:12:33] WARNING [django.request:170] Not Found: /user/adminstrator/
[08/Nov/2017 15:12:33] WARNING [django.request:170] Not Found: /favicon.ico
[08/Nov/2017 15:24:09] WARNING [django.request:170] Not Found: /user/adminstrator/
[08/Nov/2017 15:26:08] ERROR [django.request:256] Internal Server Error: /task/1/clueweb12-0206wb-80-04257.html
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/Fan/Desktop/codes/NTCIRMDB2/assessment/views.py", line 253, in show
    return render(request, a+"/"+url)
  File "/Library/Python/2.7/site-packages/django/shortcuts.py", line 67, in render
    template_name, context, request=request, using=using)
  File "/Library/Python/2.7/site-packages/django/template/loader.py", line 98, in render_to_string
    template = get_template(template_name, using=using)
  File "/Library/Python/2.7/site-packages/django/template/loader.py", line 46, in get_template
    raise TemplateDoesNotExist(template_name)
TemplateDoesNotExist: 02/clueweb12-0206wb-80-04257.html
[08/Nov/2017 15:30:51] ERROR [django.request:256] Internal Server Error: /adminstrator/
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
TypeError: admn() takes exactly 2 arguments (1 given)
[08/Nov/2017 15:57:16] ERROR [django.request:256] Internal Server Error: /task/
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/Fan/Desktop/codes/NTCIRMDB2/user_system/utils.py", line 70, in ret
    return func(*args)
  File "/Users/Fan/Desktop/codes/NTCIRMDB2/assessment/views.py", line 16, in assessment
    user_name=user.objects.filter(username ='adminstrator').username
AttributeError: 'QuerySetManager' object has no attribute 'filter'
[08/Nov/2017 16:01:50] ERROR [django.request:256] Internal Server Error: /task/
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/Fan/Desktop/codes/NTCIRMDB2/user_system/utils.py", line 70, in ret
    return func(*args)
  File "/Users/Fan/Desktop/codes/NTCIRMDB2/assessment/views.py", line 16, in assessment
    user_name=user.objects.get()
AttributeError: 'QuerySetManager' object has no attribute 'get'
[08/Nov/2017 16:02:28] ERROR [django.request:256] Internal Server Error: /task/
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/Fan/Desktop/codes/NTCIRMDB2/user_system/utils.py", line 70, in ret
    return func(*args)
  File "/Users/Fan/Desktop/codes/NTCIRMDB2/assessment/views.py", line 16, in assessment
    user_name=user.objects.username
AttributeError: 'QuerySetManager' object has no attribute 'username'
[08/Nov/2017 16:03:17] ERROR [django.request:256] Internal Server Error: /task/
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/Fan/Desktop/codes/NTCIRMDB2/user_system/utils.py", line 70, in ret
    return func(*args)
  File "/Users/Fan/Desktop/codes/NTCIRMDB2/assessment/views.py", line 16, in assessment
    user_name=user.objects.all()
AttributeError: 'QuerySetManager' object has no attribute 'all'
[08/Nov/2017 16:03:19] ERROR [django.request:256] Internal Server Error: /task/
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/Fan/Desktop/codes/NTCIRMDB2/user_system/utils.py", line 70, in ret
    return func(*args)
  File "/Users/Fan/Desktop/codes/NTCIRMDB2/assessment/views.py", line 16, in assessment
    user_name=user.objects.all()
AttributeError: 'QuerySetManager' object has no attribute 'all'
[08/Nov/2017 16:05:11] ERROR [django.request:256] Internal Server Error: /task/
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/Fan/Desktop/codes/NTCIRMDB2/user_system/utils.py", line 70, in ret
    return func(*args)
  File "/Users/Fan/Desktop/codes/NTCIRMDB2/assessment/views.py", line 16, in assessment
    user_name=user.objects.all()
NameError: global name 'user' is not defined
[08/Nov/2017 16:08:52] ERROR [django.request:256] Internal Server Error: /task/
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/Fan/Desktop/codes/NTCIRMDB2/user_system/utils.py", line 70, in ret
    return func(*args)
  File "/Users/Fan/Desktop/codes/NTCIRMDB2/assessment/views.py", line 16, in assessment
    user_name=usr.objects.all().usrid
AttributeError: 'QuerySet' object has no attribute 'usrid'
[08/Nov/2017 16:09:50] ERROR [django.request:256] Internal Server Error: /task/
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/Fan/Desktop/codes/NTCIRMDB2/user_system/utils.py", line 70, in ret
    return func(*args)
  File "/Users/Fan/Desktop/codes/NTCIRMDB2/assessment/views.py", line 17, in assessment
    user_name=u.usrid
AttributeError: 'QuerySet' object has no attribute 'usrid'
[08/Nov/2017 16:12:56] ERROR [django.request:256] Internal Server Error: /task/
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/Fan/Desktop/codes/NTCIRMDB2/user_system/utils.py", line 70, in ret
    return func(*args)
  File "/Users/Fan/Desktop/codes/NTCIRMDB2/assessment/views.py", line 16, in assessment
    user_name=usr.objects.exclude(usrid='adminstrator')
TypeError: exclude() got an unexpected keyword argument 'usrid'
[08/Nov/2017 16:14:16] ERROR [django.request:256] Internal Server Error: /task/
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/Fan/Desktop/codes/NTCIRMDB2/user_system/utils.py", line 70, in ret
    return func(*args)
  File "/Users/Fan/Desktop/codes/NTCIRMDB2/assessment/views.py", line 16, in assessment
    user_name=usr.objects.filter().exclude(usrid='adminstrator')
TypeError: exclude() got an unexpected keyword argument 'usrid'
[08/Nov/2017 16:14:18] ERROR [django.request:256] Internal Server Error: /task/
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/Fan/Desktop/codes/NTCIRMDB2/user_system/utils.py", line 70, in ret
    return func(*args)
  File "/Users/Fan/Desktop/codes/NTCIRMDB2/assessment/views.py", line 16, in assessment
    user_name=usr.objects.filter().exclude(usrid='adminstrator')
TypeError: exclude() got an unexpected keyword argument 'usrid'
[08/Nov/2017 16:14:20] ERROR [django.request:256] Internal Server Error: /task/
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/Fan/Desktop/codes/NTCIRMDB2/user_system/utils.py", line 70, in ret
    return func(*args)
  File "/Users/Fan/Desktop/codes/NTCIRMDB2/assessment/views.py", line 16, in assessment
    user_name=usr.objects.filter().exclude(usrid='adminstrator')
TypeError: exclude() got an unexpected keyword argument 'usrid'
[08/Nov/2017 16:16:02] ERROR [django.request:256] Internal Server Error: /task/
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/Fan/Desktop/codes/NTCIRMDB2/user_system/utils.py", line 70, in ret
    return func(*args)
  File "/Users/Fan/Desktop/codes/NTCIRMDB2/assessment/views.py", line 16, in assessment
    user_name=usr.objects.filter().usrid
AttributeError: 'QuerySet' object has no attribute 'usrid'
[08/Nov/2017 16:18:37] ERROR [django.request:256] Internal Server Error: /task/
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/Fan/Desktop/codes/NTCIRMDB2/user_system/utils.py", line 70, in ret
    return func(*args)
  File "/Users/Fan/Desktop/codes/NTCIRMDB2/assessment/views.py", line 16, in assessment
    user_name=usr.objects.get().usrid
  File "/Library/Python/2.7/site-packages/mongoengine/queryset/base.py", line 247, in get
    raise queryset._document.MultipleObjectsReturned(message)
MultipleObjectsReturned: 114 items returned, instead of 1
[08/Nov/2017 16:19:23] ERROR [django.request:256] Internal Server Error: /task/
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/Fan/Desktop/codes/NTCIRMDB2/user_system/utils.py", line 70, in ret
    return func(*args)
  File "/Users/Fan/Desktop/codes/NTCIRMDB2/assessment/views.py", line 16, in assessment
    user_name=usr.objects.get(topicid='1').usrid
  File "/Library/Python/2.7/site-packages/mongoengine/queryset/base.py", line 247, in get
    raise queryset._document.MultipleObjectsReturned(message)
MultipleObjectsReturned: 41 items returned, instead of 1
[08/Nov/2017 16:24:54] ERROR [django.request:256] Internal Server Error: /task/
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/Fan/Desktop/codes/NTCIRMDB2/user_system/utils.py", line 70, in ret
    return func(*args)
  File "/Users/Fan/Desktop/codes/NTCIRMDB2/assessment/views.py", line 16, in assessment
    user_name=usr.objects.filter(usrid__contains='user').usrid
AttributeError: 'QuerySet' object has no attribute 'usrid'
[08/Nov/2017 16:26:25] ERROR [django.request:256] Internal Server Error: /task/
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/Fan/Desktop/codes/NTCIRMDB2/user_system/utils.py", line 70, in ret
    return func(*args)
  File "/Users/Fan/Desktop/codes/NTCIRMDB2/assessment/views.py", line 16, in assessment
    user_name=usr.objects.filter(usrid__contains='user').usrid
AttributeError: 'QuerySet' object has no attribute 'usrid'
[08/Nov/2017 16:28:17] ERROR [django.request:256] Internal Server Error: /task/
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/Fan/Desktop/codes/NTCIRMDB2/user_system/utils.py", line 70, in ret
    return func(*args)
  File "/Users/Fan/Desktop/codes/NTCIRMDB2/assessment/views.py", line 16, in assessment
    user_name=usr.objects.values_list('usrid').distinct()
TypeError: distinct() takes exactly 2 arguments (1 given)
[08/Nov/2017 16:28:37] ERROR [django.request:256] Internal Server Error: /task/
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/Fan/Desktop/codes/NTCIRMDB2/user_system/utils.py", line 70, in ret
    return func(*args)
  File "/Users/Fan/Desktop/codes/NTCIRMDB2/assessment/views.py", line 16, in assessment
    user_name=usr.objects.values_list('usrid').set()
AttributeError: 'QuerySet' object has no attribute 'set'
[08/Nov/2017 16:28:53] ERROR [django.request:256] Internal Server Error: /task/
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/Fan/Desktop/codes/NTCIRMDB2/user_system/utils.py", line 70, in ret
    return func(*args)
  File "/Users/Fan/Desktop/codes/NTCIRMDB2/assessment/views.py", line 16, in assessment
    user_name=user.objects.values_list('usrid')
AttributeError: 'QuerySetManager' object has no attribute 'values_list'
[08/Nov/2017 16:29:03] ERROR [django.request:256] Internal Server Error: /task/
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/Fan/Desktop/codes/NTCIRMDB2/user_system/utils.py", line 70, in ret
    return func(*args)
  File "/Users/Fan/Desktop/codes/NTCIRMDB2/assessment/views.py", line 16, in assessment
    user_name=usr.objects.values_list('usrid')
AttributeError: 'QuerySetManager' object has no attribute 'values_list'
[08/Nov/2017 16:30:22] ERROR [django.request:256] Internal Server Error: /task/
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/Fan/Desktop/codes/NTCIRMDB2/user_system/utils.py", line 70, in ret
    return func(*args)
  File "/Users/Fan/Desktop/codes/NTCIRMDB2/assessment/views.py", line 20, in assessment
    user_name.set()
AttributeError: 'list' object has no attribute 'set'
[08/Nov/2017 18:02:17] WARNING [django.request:170] Not Found: /setlist/
[08/Nov/2017 18:02:20] WARNING [django.request:170] Not Found: /setlist/
